#+TITLE: Seminar 2 Notes


* Prompt: You are part of a program to train other cadets about /consent/ and /sexual violence/.
Present 2 idea that you consider crucial to the intersection of Cadet Life, power, and consent.

* What is Consent?

From an external point of view, "consent" can be seen simply as permission (If one receives someone's /consent/ to perform an action, they are receiving permission).
From an internal perspective however, it is seen as an acceptance, desire, or otherwise general willingness to be a part of a given situation, action, or similar. 

* Consent and Cadet Life
Obvious sexual connotation. Relationships depend on consent, and given that the vast majority of CGA's population is about 20, there is bound to be a focus on romance and some degree of sexual interaction. This depends entirely on consent.
Beside that, Consent plays a large role in cadet life - abuse of power (forcing 4/c to take duty), group work (either in classes or within divisions), and Team dynamics (respect, trust) all rely on a basis of fundamental consent. 4/c must /consent/ to take duty, members of a group must /consent/ to complete the assigned work (or must /consent/ to accept a specific member as the designated leader), and team dynamics can be easily ruined by one or two members failing to respect the larger groups consent.

* Points I consider crucial to a potential training on consent

** A. Different situations require different levels of consent
It can reasonably be said that there are different levels of consent.
- When seeking sexual intercourse with another person, one ought to seek explicitly voiced, absolute consent (I want to...) or concede to the absence of such.
- In less sensitive situations where consent is a factor (group work for example) implicit consent is acceptable (where the lack of objection to a suggestion can be interpreted as universal agreement, or at least acceptance).


*** Supporting Argument 1
It's important to recognize these different levels of consent, and the situations in which they are necessary. Conly said something similar in "Seduction, Rape, and Coercion" when she differentiated between coercion and something more serious. Conly argued that, while words can constitute rape, the differntiating factor is the threat of violence. She describes elements of emotional pressure and coercive reasoning that are intrinsic to everyday life, making the point that these types of psychological pressure are common in many benign situations, and that they only become an issue when they are applied with the intention of harm or deliberate exploitation. Similarly, consent is woven into many mundane aspects of everyday life, but when we start approaching potentially harmful issues the need for cnsent becomes much clearer.

**** Potential Counter Argument
If we focus too heavily on differentiating between different "levels" of consent, it might become too easy to "misrepresent" a situation, with someone claiming implied consent rather than taking responsibility for their actions. If we too heavily qualify the need for consent, then we risk devaluing the entire issue.

***** Rebuttal
While it is true that some may use misinterpretation as a possible justification for misdeeds, this is not a valid excuse for ignoring the need for consent. As it is, the purpose of training is to properly educate and prepare the trainee for situations in which they might have to make such judgements. In so doing, the culpability shits from the organization to the member, at which point the individual is now responsible for all of the actions they make. Any potential solutions will have possible points of exploitation, it's more important to consider the effect such training will have on the community as a whole.

*** Supporting Argument 2
This idea of varying levels of consent is part of what makes positions of power so easy to abuse. When someone is in a position where they have influence and power over others, there is a certain level of assumed liberty that they are allowed. In many cases, it becomes a thin line seperating a justifiable amount of assumed control from an entirely unacceptable amount of power that one person is exercising over another, and it is because we have to assume some level of consent as a leader in order to accomplish our goals, the key is knowing when to stop. ONeill talks a great deal about similar ideas, discussing the difference between Hypothetical Consent, Significant and Spurious Consent, and Possible Consent. She aligns this idea with Kantian Ethics, focusing on differentiating between desire and consent. In the end, her description of maxims and the slippery slope of deception, power, and collaboration vs coercion describes many ideas that are tangential to the idea of varying consent. 

**** Potential Counter Argument
While abuse of power is absolutel an issue, it has little to do with this idea of "varying consent". Abuse of power is just that, someone with influence and control exerting that control over someone who cannot resist. There is no consent at all in this situation.

***** Rebuttal
That is true - someone who deliberately abuses power is eliminating any semblance of consent. But that is not who this training would be directed at - someone who commits deliberate rape would not change their mind because of a training -  the only potential way to stop that would be punishment, or other /preventative/ measures. This training is meant to educate the average person about how to recognize when they themselves might be unintentionally or peripherally abusing their own power. Abuse of power is one of those things that becomes easy to overlook the more ccustomed to your power you are. If you are properly trained on how to properly behave, then accidents, misunderstandings, and other similar events are less likely to occur.

** B. Consent should be part of daily conversation
In order for training to be effective, the issues that it covers need to become part of the daily narrative in the workspace. This doesn't mean that every conversation needs to begin with "Do you consent to..." - that's somewhat extreme. But people should feel comfortable talking about what consent entails, and how it applies to various parts of daily life. 

*** Supporting Argument 1
Many of the trainings at the academy quickly become meaningless.We are inundated with meetings, assignments, trainings, emails, and various peripheral responsibilities. Among all of this, it seems rather pointless to even attempt to recall what each training covers or how it is relevant to our everyday lives. Despite this, some trainings seem more influential or memorable than others. This is because they give the Corps something to talk about. When trainings present an issue as something that should be cause for discourse, it seems to cement itself into out minds - becoming something that we accept as reality. This is what needs to happen when discussing consent. Most people would agree that consent is important, but they will do it with a vague sense of discomfort because, despite being one of the foundations of a functioning society, it is somehow seen as "taboo" or "unfit for polite company". This isn't explicitly discussed in any of the readings (as far as I saw) but each of these articles inherently supports the idea that it is important to bring such topics into normal conversation.

**** Potential Counter Argument
Yes it's important to talk about issues like this - but do they really need to be part of daily conversation? The average person doesn't alk about this sort of thing, and the do perfectly fine. 

***** Rebuttal
That's true, but you can't deny that this has been, and continues to be, an issue. We don't solve issues by simply ignoring them and continuing on as we have, we solve them by enacting change and addressing some of the root causes of issues like these. 

*** Supporting Argument 2
When discussing contentious issues, the best way to help as many people understand as possible is to foster discourse. People are more likely to develop their own opinions and understanding for a topic if they enter into an active conversation about it. It's one thing to present information and have someone understand it, but with social issues like this it's important to ensure that everyone has a firm grasp on the social basis for the concept in question, so that, when confronted by a situation different from what they initially learned about, they will be able to make decisions based on their own personal grasp of the topic. 

**** Potential Counter Argument
While it's certainly ideal that everyone involved has a deep fundamental understanding of the issue at hand, is it not somewhat unrealistic to expect everyone to attain this level of understanding?

***** Rebuttal
Given the environment in which we would be giving this training, no I do not consider it a stretch. We would be giving this training with the expectation that everyone involved actively interact with the training; and given that this is a basic facet of everyday life, it isn't too much to assume that Coast Guard Academy Cadets would be able to adopt these ideas. 

* How would the readings manifest themselves in this training?
Ideas from all of these readings would certainly be part of the material presented during a hypothetical training on consent. O'Neill's article on "Treating Others as Persons" was particularly relevant, and the Kantian ideals he represents, while beyond the scope of such a training, would help build the goundwork for the ethical ideals we would be building our information off of. Additionally, Brison's article on the harms of sexual violence is a powerful statement to the damage that such inhumane actions can cause. 
